MyPersonnalBlog/Controllers/BlogueController.cs
using MyPersonnalBlog.api.Controllers;
using MyPersonnalBlog.Models;
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Web.Mvc;

namespace MyPersonnalBlog.Controllers
{
    public class BlogueController : Controller
    {
        private BlogRepo _bloguesRepo = new BlogRepo();
        private UsersRepo _usersRepo = new UsersRepo();
        private TagsRepo _tagsRepo = new TagsRepo();
        public ActionResult Index()
        {
            string nomUsager = Session["LoggedUser"] as string;
            User usager = _usersRepo.GetByUserName(nomUsager);

            if (usager != null)
                return View(usager.BlogPosts.ToList());

            Session["LoggedUser"] = null;
            return RedirectToAction("Index", "Authentification");
        }

        public ActionResult Details(int? id = null)
        {
            var entite = ExtraireEntite(id);
            ViewBag.Tags = _tagsRepo.GetTags();

            return View(entite);
        }

        [HttpPost]
        public ActionResult Details(BlogPost entite)
        {
            ViewBag.Tags = _tagsRepo.GetTags();
            string nomUsager = Session["LoggedUser"] as string;
            User usager = _usersRepo.GetByUserName(nomUsager);
            entite.UserId = usager.UserId;
            if (!ModelState.IsValid)
                return View(entite);

            TryUpdateModel(entite);
            var tags = Request["Tags"] != null ?
                Request["Tags"].Split(new[] { "," }, System.StringSplitOptions.RemoveEmptyEntries) :
                new List<string>().ToArray();
            int resultat;
            if (entite.Id == 0)
            {
                entite.CreateTime = DateTime.Now;
                resultat = _bloguesRepo.AddBlog(entite, tags);
            }
            else
            {
                resultat = _bloguesRepo.UpdateBlog(entite, tags);
            }

            if (resultat != 0) return RedirectToAction("Index");
            ModelState.AddModelError(string.Empty, "oops! veuillez réessayer de nouveau!");
            return View(entite);
        }

        private BlogPost ExtraireEntite(int? id)
        {
            return id == null ?
            new BlogPost()
            : _bloguesRepo.GetBlogById(id.GetValueOrDefault());
        }
    }
}

MyPersonnalBlog/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Test De Programmeur", "Index", "Blogue", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Blogue", "Index", "Blogue")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Mon Test De Programmeur</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>