MyPersonnalBlog/Controllers/AuthentificationController.cs
using MyPersonnalBlog.Models;
using System;
using System.Linq;
using System.Security.Cryptography;
using System.Text;
using System.Web.Mvc;

namespace MyPersonnalBlog.Controllers
{
    public class AuthentificationController : Controller
    {
        private UsersRepo _usersRepo = new UsersRepo();

        public ActionResult Index()
        {
            string nomUsager = Session["LoggedUser"] as string;

            if (!string.IsNullOrEmpty(nomUsager))
                return RedirectToAction("Index", "Blogue");

            return View(new User());
        }

        [HttpPost]
        public ActionResult Index(User entree)
        {
            string motdepassechiffrer = GenererMd5(entree.Password);
            var usager = _usersRepo.GetByUserNameAndPassword(entree.Username, motdepassechiffrer);
            if (usager != null)
            {
                Session["LoggedUser"] = usager.Username;
                return RedirectToAction("Index", "Blogue");
            }
            ModelState.AddModelError(string.Empty, new Exception("user not found"));
            return View(entree);
        }

        private static string GenererMd5(string password)
        {
            string result;
            using (MD5 hash = MD5.Create())
            {
                result = String.Join
                (
                    "",
                    from ba in hash.ComputeHash
                    (
                        Encoding.UTF8.GetBytes(password)
                    )
                    select ba.ToString("x2")
                );
            }

            return result;
        }
    }
}

MyPersonnalBlog/Views/Authentification/Index.cshtml
@model MyPersonnalBlog.Models.User
@{
    ViewBag.Title = "Page Authentification";
}
<style>
    html,
    body {
        height: 100%;
    }

    .navbar{
        display:none;
    }

    body {
        display: -ms-flexbox;
        display: -webkit-box;
        display: flex;
        -ms-flex-align: center;
        -ms-flex-pack: center;
        -webkit-box-align: center;
        align-items: center;
        -webkit-box-pack: center;
        justify-content: center;
        padding-top: 40px;
        padding-bottom: 40px;
        background-color: #f5f5f5;
    }

    footer p {
        text-align: center;
    }
</style>
@using (Html.BeginForm("Index", "Authentification", FormMethod.Post,
                                    new { enctype = "multipart/form-data", @Class = "form-signin" }))
{
    <h1 class="h3 mb-3 font-weight-normal">Veuillez ouvrir une session</h1>
    @Html.ValidationSummary(true, "Usager non trouvé ou bien mauvais mot de passe")
    <label for="Usager" class="sr-only">Courriel</label>
    @Html.LabelFor(d => d.Username, "Usager")
    @Html.TextBoxFor(d => d.Username, new { @Class = "form-control", placeholder = "Usager", required = "", autofocus = "" })
    @Html.LabelFor(d => d.Password, "Mot de passe")
    @Html.TextBoxFor(d => d.Password, new { type = "password", @Class = "form-control", placeholder = "Mot de passe", required = "" })
    <button class="btn btn-lg btn-primary btn-block" type="submit">Ouvrir Session</button>
}